server:
  port: 10517
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
spring:
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      url: jdbc:mysql://119.23.10.167:3306/agro-achievement?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
      username: root
      password: Hyx123!_
      driver-class-name: com.mysql.cj.jdbc.Driver
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  mail:
          default-encoding: utf-8
          host: smtp.126.com
          #发送者的邮箱密码
          password: 123456huyaxing
          #端口
          port: 25
          #协议
          protocol: smtp
          #发送者的邮箱账号
          username: huystar@126.com
  resources:
    static-locations: classpath:/

#mybatis plus配置
mybatis-plus:
  #由于本例中采用注解方式编写sql，故而此处可不配置
  #mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: org.wlgzs.agro_achievement
  #枚举扫描配置（本示例未使用到）
  #typeEnumsPackage: com.szss.admin.model.domain
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      table-underline: true
      #column-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #序列接口实现类配置,在新的mybatis-plus-boot-starter中不推荐此方式进行配置,推荐自定义bean注入
      #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器(由于本例中采用注解方式编写sql，故而不需要刷新mapper.xml文件)
    refresh: true
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    #sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false